namespace DuckDB.NET.Native;

public enum DuckDBStatementType
{
    Invalid = 0,
    Select = 1,
    Insert = 2,
    Update = 3,
    Explain = 4,
    Delete = 5,
    Prepare = 6,
    Create = 7,
    Execute = 8,
    Alter = 9,
    Transaction = 10,
    Copy = 11,
    Analyze = 12,
    VariableSet = 13,
    CreateFunc = 14,
    Drop = 15,
    Export = 16,
    Pragma = 17,
    [Obsolete("DuckDB reports SHOW statements as Select.")]
    Show = Select,
    Vacuum = 18,
    Call = 19,
    Set = 20,
    Load = 21,
    Relation = 22,
    Extension = 23,
    LogicalPlan = 24,
    Attach = 25,
    Detach = 26,
    Multi = 27,
    CopyDatabase = 28,
    UpdateExtensions = 29,
    MergeInto = 30,
}
